### ISSUE TITLE
YAML -> JSON or JSON -> JSON?

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-registry#10]
Should the registry be maintained as YAML or JSON?

YAML is indent-based and cleaner to read (without all the double-quotes). Might make it marginally easier to maintain.

Either way, we will still have a build step and still output to JSON.

**Comment by fernandojsg** [comment]
I don't really care about one or another, but maybe js devs are more used to use json over yaml?

**Comment by ngokevin** [comment]
Stayed with YML for now...might be less error prone (forgetting a quote, extra commas, etc0

**Comment by dmarcos** [comment]
YML means compilation, more tooling, more moving pieces, more formats... I would stick with JSON. It's already pretty legible and easy to edit. I think the marginal gains that YAML brings are not worth the complexity

**Comment by ngokevin** [comment]
We distribute JSONs so there's no difference to consuming applications.

On the backend/registry side, there's a build/compilation step regardless. The YAML conversion part of that is 1LOC: https://github.com/aframevr/aframe-registry/blob/master/scripts/build.js
