### ISSUE TITLE
update aframevr.github.io/aframe-registry/ page to prototype the inspector design

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-registry#14]
<img width="961" alt="screen shot 2016-09-22 at 5 13 36 pm" src="https://cloud.githubusercontent.com/assets/674727/18770149/edd10658-80e7-11e6-9ea3-1a525d7f168b.png">

**Comment by fernandojsg** [comment]
What about leaving this one open until we'll have a filter? :angel:

**Comment by feiss** [comment]
hey @ngokevin , will try to get this done for wednesday

**Comment by ngokevin** [comment]
Wonder if we should have different designs for the Registry frontend vs. Inspector frontend. Registry should probably be A-Frame branded since it will interact with more pieces than the Inspector (to also just browse online or from other tools). Maybe it'd just be a matter of dark vs. light theme.

**Comment by fernandojsg** [comment]
Yep maybe we could have two css using the same html?

**Comment by ngokevin** [comment]
There may be some functional differences as well. The Registry in relation to the Inspector would expose buttons to install them to the Inspector, whereas the Registry Frontend would just have CDN links.
