### ISSUE TITLE
Merge aframe-shaders into this repo

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-registry#17]
We're no longer using https://github.com/aframevr/aframe-shaders so we could close that repo and add another entry here to store the community shaders.

**Comment by fernandojsg** [comment]
@dmarcos @ngokevin we agree on this one too right?

**Comment by ngokevin** [comment]
Yeah. The shader entry is in, just need to update the Inspector branch.

**Comment by fernandojsg** [comment]
:+1:
