### ISSUE TITLE
Incorrect npmUrl (Missing .com)

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-registry#21]
Currently: `https://npmjs/package/aframe-stereo-component`
Expected: `https://npmjs.com/package/aframe-stereo-component`

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-registry/commit/eed374a4fb4bc50026e862c4297f0b3353369713

**Comment by fernandojsg** [comment]
Remember to rebuild :D
