### ISSUE TITLE
Discuss where Inspector display/presentation metadata should live/look like

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-registry#22]
We've discussed ordering, grouping, sorting of A-Frame component properties for display in the Inspector. 

- Should that live in the component or registry?
- Format of the Inspector-specific metadata?

Within the component sounds easiest, but I'm a little worried it couples the component to the Inspector. Putting the metadata elsewhere for purely display purposes seems technically cleaner in terms of abstraction.

**Comment by fernandojsg** [comment]
Do you mean adding things like `tags` right? In that case I believe it could be better to live here in the registry so we could modify them, and it will work both for the registry webpage or the inspector and we don't rely on the component package in case we want to rename some tags or whatever

**Comment by ngokevin** [comment]
Like grouping and sorting of properties in the Inspector Components panel.

**Comment by fernandojsg** [comment]
Ah ok, that properties probably should stay on the component, so each one could decide how the component will be shown on the inspector, or just use the default visualization and don't define anything. Similar to how unity plugins works, you can just place there the parameters or get fancy and define a much nicer UI

**Comment by ngokevin** [comment]
So an `inspector` (aframe?) package.json field?

**Comment by dmarcos** [comment]
Per component / property inspector hints should live in the component schema.

**Comment by fernandojsg** [comment]
Yes, I don't like using package.json for that, I think it should belong to the component definition file, inside the schema or wherever.

**Comment by ngokevin** [comment]
overloading the schema feels okay now as the Inspector becomes more and more important.
