### ISSUE TITLE
Populate Inspector-ready components

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-registry#25]
Will start populating with components that would do well from the Inspector (i.e., have an immediate visual effect that don't need to be composed with other components).
- [ ] ocean
- [x] particle-system
- [x] physics

There are other great components that function better from code/HTML...we can perhaps add those after.

**Comment by donmccurdy** [comment]
I've pulled physics into its own repo, [aframe-physics-system](https://github.com/donmccurdy/aframe-physics-system) (better ideas on naming?), with the exception of `kinematic-body`.  I'm going to put `kinematic-body` into aframe-extras.misc instead, to discourage it more actively for VR apps.

**Comment by ngokevin** [comment]
That sounds good, want to do the honors of updating the registry?
