### ISSUE TITLE
Support dependencies

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-registry#47]
If a component specifies dependency components (on other components in the Registry):

- The Inspector will install the dependency components before the main component.
- angle will install the dependency components before the main component.

This will allow for components to build on top of each other (e.g., a component can use animations).

**Comment by dmarcos** [comment]
How do components specify the versions of the components they depend on

**Comment by ngokevin** [comment]
Registry handles versioning. When you install 0.4.0 version of component `foo`, it will install 0.4.0 version of component `bar`.

**Comment by dmarcos** [comment]
What happens if component `foo` uses version `0.2.3` of component `bar` and version `0.3.4` of component `xyz`?

**Comment by dmarcos** [comment]
How can components lock to a specific version of the dependencies?

**Comment by dmarcos** [comment]
Can two components `x` and `y` depend on different versions of the component `z`?

**Comment by dmarcos** [comment]
What happens if components bundle dependencies with them?

**Comment by machenmusik** [comment]
namespace clashes, which could be fixed if component map keys have versioning, and there is wildcard-like matching as npm does... ?
