### ISSUE TITLE
Point clouds (New Component?)

### ISSUE THREAD

**Issue by eric-schleicher** [aframevr/aframe-registry#49]
I would like to load point clouds in a-frame.  is this the right place to implement and commit?  willing to write it.  

is there another components that makes sense to adapt?

**Comment by ngokevin** [comment]
Yeah, if you write one, you can submit it for review!

Whatever you find missing or would be useful would be a good component to adapt.

**Comment by ngokevin** [comment]
Let us know when you have it!

**Comment by eric-schleicher** [comment]
i will.  i want to make this so bad...
