### ISSUE TITLE
Automate generation of JSON when a new version of aframe is deployed?

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-registry#78]
As every time we deploy a new version of aframe we forget to generate and publish a new version of the registry and the inspector keep showing an error that the newest version can't be loaded :)

**Comment by fernandojsg** [comment]
@ngokevin @dmarcos what do you think about it? Are we going to put any more effort on the registry or just stop using it? We need a decision as with every new release the inspector gets broken because of the missing version json.

**Comment by ngokevin** [comment]
I would remove integration from Inspector as the Registry builds are not maintained. We can push updates to Inspector after the fact, if we want to fix, we can push 0.7.8.

**Comment by fernandojsg** [comment]
Ok, removing it. https://github.com/aframevr/aframe-inspector/pull/537
