### ISSUE TITLE
Current Registry 404 Error

### ISSUE THREAD

**Issue by CBernsCode** [aframevr/aframe-registry#87]
It seems like the inspector is looking for the component registry at: https://aframe.io/aframe-registry/build/0.7.0.json. This is sending a 404 error back and preventing the inspector from opening. 
![image](https://user-images.githubusercontent.com/8380478/36343828-eb778da6-13de-11e8-8ef1-3abfaa6a339d.png)

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/aframe-registry/issues/78
