### ISSUE TITLE
Rename to registry?

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-registry#9]
Later on, assets/shaders/controls/effects/etc., could live here. It might save us trouble later to name it appropriately now.

`aframe-registry` is nice since it's agnostic on the type of asset. And `aframe-components` sounds like the actual components/files live here, rather than just referencing them.

**Comment by fernandojsg** [comment]
Yep I like that. At first I thought to be more explicit like `aframe-components-registry` but then I thought that we could use it for any other kind of `registry` let's say assets samples or whatever.
:+1:

**Comment by ngokevin** [comment]
OK, let's rename it and see how it goes.
